package com.zhaoyunfei.javacc.module.parser;/* Generated By:JavaCC: Do not edit this line. ActionParserConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ActionParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER = 5;
  /** RegularExpression Id. */
  int LPAREN = 6;
  /** RegularExpression Id. */
  int RPAREN = 7;
  /** RegularExpression Id. */
  int COMMA = 8;
  /** RegularExpression Id. */
  int IF = 9;
  /** RegularExpression Id. */
  int FOR = 10;
  /** RegularExpression Id. */
  int WHILE = 11;
  /** RegularExpression Id. */
  int BREAK = 12;
  /** RegularExpression Id. */
  int CONTINUE = 13;
  /** RegularExpression Id. */
  int CONTINUE_END = 14;
  /** RegularExpression Id. */
  int DO = 15;
  /** RegularExpression Id. */
  int END = 16;
  /** RegularExpression Id. */
  int THEN = 17;
  /** RegularExpression Id. */
  int PTP = 18;
  /** RegularExpression Id. */
  int LIN = 19;
  /** RegularExpression Id. */
  int ARC = 20;
  /** RegularExpression Id. */
  int CIRCLE = 21;
  /** RegularExpression Id. */
  int LESSTHAN = 22;
  /** RegularExpression Id. */
  int LESSTHANOREQUAL = 23;
  /** RegularExpression Id. */
  int GREATERTHAN = 24;
  /** RegularExpression Id. */
  int GREATERTHANOREQUAL = 25;
  /** RegularExpression Id. */
  int EQUALTO = 26;
  /** RegularExpression Id. */
  int EQUAL = 27;
  /** RegularExpression Id. */
  int ADD = 28;
  /** RegularExpression Id. */
  int NOTEQUAL = 29;
  /** RegularExpression Id. */
  int TRUE = 30;
  /** RegularExpression Id. */
  int FALSE = 31;
  /** RegularExpression Id. */
  int IDENTIFIER = 32;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<NUMBER>",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"if\"",
    "\"for\"",
    "\"while\"",
    "\"break\"",
    "\"goto continue\"",
    "\"::continue::\"",
    "\"do\"",
    "\"end\"",
    "\"then\"",
    "\"PTP\"",
    "\"Lin\"",
    "\"ARC\"",
    "\"Circle\"",
    "\"<\"",
    "\"\\u2264\"",
    "\">\"",
    "\"\\u2265\"",
    "\"=\"",
    "\"==\"",
    "\"+\"",
    "\"\\u2260\"",
    "\"true\"",
    "\"false\"",
    "<IDENTIFIER>",
  };

}
